package Chargemonk::Model::Chargemonk;

use strict;
use Chargemonk;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Chargemonk::Schema',
    connect_info => Chargemonk->config->{db_engine} eq 'pg'
    ? { dsn         => 'dbi:Pg:dbname=' . Chargemonk->config->{pg_dbname} . ';host=' . Chargemonk->config->{pg_host},
        user        => Chargemonk->config->{pg_user},
        password    => Chargemonk->config->{pg_password},
        quote_names => 1,
        }
    : Chargemonk->config->{db_engine} eq 'mysql' ? {
        dsn         => 'DBI:mysql:database=' . Chargemonk->config->{mysql_dbname} . ';host=' . Chargemonk->config->{mysql_host},
        user        => Chargemonk->config->{mysql_user},
        password    => Chargemonk->config->{mysql_password},
        quote_names => 1,
        }
    : {},
);

=head1 NAME

Chargemonk::Model::Chargemonk - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Chargemonk>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Chargemonk::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

dev

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
